// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rriwipacgptdxjblkhiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyaXdpcGFjZ3B0ZHhqYmxraGl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNTE0NTYsImV4cCI6MjA2NzkyNzQ1Nn0.WILSWLtbPYhUKor_XwI6UgVApSaoxB99UPPIheHMDOA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});